# Generated by Django 5.1.4 on 2025-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStructure',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم القسم')),
                ('department_name', models.CharField(max_length=100, verbose_name='اسم قسم الشرطة')),
                ('directorate_security', models.CharField(max_length=100, verbose_name='إدارة أمن المديرية')),
                ('province_security', models.CharField(max_length=100, verbose_name='إدارة أمن المحافظة')),
            ],
            options={
                'verbose_name': 'قسم شرطة',
                'verbose_name_plural': 'الأقسام الشرطية',
            },
        ),
    ]
