# Generated by Django 5.1.4 on 2025-04-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crimes', '0001_initial'),
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('investigation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الإجراء')),
                ('status', models.CharField(choices=[('مقبوض', 'مقبوض'), ('هارب', 'هارب')], default='مقبوض', max_length=50, verbose_name='حالة التحقيق')),
                ('arrest_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبض')),
                ('detention_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيف')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإفراج')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النقل')),
                ('arrest_method', models.TextField(blank=True, null=True, verbose_name='كيفية القبض')),
                ('arresting_officer', models.CharField(blank=True, max_length=100, null=True, verbose_name='ضابط القبض')),
                ('transferred_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='نقل إلى')),
                ('released_on_bail', models.BooleanField(default=False, verbose_name='إفراج بضمان؟')),
                ('bail_guarantor', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الضامن')),
                ('case_closed', models.BooleanField(default=False, verbose_name='انتهت القضية؟')),
                ('procedure_stopped', models.BooleanField(default=False, verbose_name='وقف الإجراءات؟')),
                ('referred_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإحالة إلى')),
                ('issuing_authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='السلطة الآمرة')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='crimes.crime', verbose_name='الجريمة')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='suspects.suspect', verbose_name='المتهم')),
            ],
            options={
                'verbose_name': 'إجراء تحري',
                'verbose_name_plural': 'إجراءات التحري',
                'ordering': ['-arrest_date'],
                'unique_together': {('crime', 'suspect')},
            },
        ),
    ]
