# Generated by Django 5.1.1 on 2024-10-28 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=3)),
                ('donation_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('expired', 'Expired'), ('reserved', 'Reserved')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
            ],
        ),
    ]
