# Generated by Django 5.1.4 on 2024-12-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodunit',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
