# Generated by Django 5.1.4 on 2025-04-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crimes', '0001_initial'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prosecution',
            fields=[
                ('prosecution_id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الإجراء')),
                ('prosecutor_office', models.CharField(max_length=100, verbose_name='النيابة المختصة')),
                ('case_number', models.CharField(max_length=50, verbose_name='رقم القضية')),
                ('submission_date', models.DateField(verbose_name='تاريخ تقديم القضية للنيابة')),
                ('prosecutor_decisions', models.TextField(verbose_name='قرارات النيابة')),
                ('referral_to_court_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإحالة إلى المحكمة')),
                ('court_procedures', models.TextField(blank=True, null=True, verbose_name='إجراءات المحكمة')),
                ('verdict', models.TextField(blank=True, null=True, verbose_name='منطوق الحكم')),
                ('sentence_execution', models.TextField(blank=True, null=True, verbose_name='تنفيذ العقوبة')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosecutions', to='crimes.crime', verbose_name='الجريمة')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosecutions', to='investigations.investigation', verbose_name='إجراء التحري')),
            ],
            options={
                'verbose_name': 'إجراء نيابة',
                'verbose_name_plural': 'إجراءات النيابة',
                'unique_together': {('crime', 'investigation')},
            },
        ),
    ]
