# Generated by Django 5.1.1 on 2024-12-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantity_in_ml', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'متوفر'), ('Reserved', 'محجوز'), ('Expired', 'منتهي الصلاحية')], max_length=20)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='Donation.donation')),
            ],
        ),
    ]
