# Generated by Django 5.1.1 on 2024-12-28 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentname', models.CharField(max_length=65)),
                ('agents_ac_no', models.CharField(max_length=6, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=65, null=True)),
                ('telephone', models.CharField(blank=True, max_length=21, null=True)),
                ('fax', models.CharField(blank=True, max_length=21, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=15, null=True)),
                ('town', models.CharField(blank=True, max_length=35, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('road_street', models.CharField(blank=True, max_length=65, null=True)),
                ('building', models.CharField(blank=True, max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('countrycode', models.CharField(max_length=10, unique=True)),
                ('subscriber', models.CharField(blank=True, max_length=19, null=True)),
                ('nationality', models.CharField(blank=True, max_length=150, null=True)),
                ('currency', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=35)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('sale', models.BooleanField(default=False)),
                ('expense', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(max_length=5)),
                ('doc_type', models.CharField(max_length=25)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('accounts', models.SmallIntegerField(blank=True, null=True)),
                ('cooperative', models.SmallIntegerField(blank=True, null=True)),
                ('payroll', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=40)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('middlename', models.CharField(blank=True, max_length=15, null=True)),
                ('pp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('idno', models.IntegerField(blank=True, null=True)),
                ('countrycode', models.CharField(max_length=2)),
                ('pobox', models.CharField(blank=True, max_length=10, null=True)),
                ('town', models.CharField(blank=True, max_length=30, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mobilephone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=1)),
                ('occupancy', models.CharField(max_length=1)),
                ('rate_type', models.CharField(max_length=1)),
                ('bo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('bb', models.DecimalField(decimal_places=0, max_digits=10)),
                ('hb', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fb', models.DecimalField(decimal_places=0, max_digits=10)),
                ('currency', models.CharField(max_length=45)),
                ('date_started', models.DateField()),
                ('date_stopped', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField()),
                ('doc_type', models.CharField(max_length=15)),
                ('doc_no', models.IntegerField()),
                ('doc_date', models.DateField()),
                ('details', models.CharField(max_length=65)),
                ('dr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('sname', models.CharField(max_length=25)),
                ('loginname', models.CharField(max_length=15, unique=True)),
                ('pass_field', models.CharField(max_length=32)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('fax', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=65, null=True)),
                ('dateregistered', models.DateField(blank=True, null=True)),
                ('countrycode', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('date_billed', models.DateTimeField()),
                ('billno', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('date_checked', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('book_id', 'billno')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=1)),
                ('meal_plan', models.CharField(max_length=2)),
                ('no_adults', models.SmallIntegerField(blank=True, null=True)),
                ('no_child', models.SmallIntegerField(blank=True, null=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('residence_id', models.CharField(blank=True, max_length=2, null=True)),
                ('payment_mode', models.SmallIntegerField(blank=True, null=True)),
                ('roomid', models.IntegerField()),
                ('checkedin_by', models.IntegerField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=15, null=True)),
                ('billed', models.SmallIntegerField(blank=True, null=True)),
                ('checkout_by', models.IntegerField(blank=True, null=True)),
                ('codatetime', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotele.agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotele.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotele.guest')),
                ('payment_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotele.paymentmode')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotele.rate'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_through', models.CharField(max_length=15)),
                ('reservation_by', models.CharField(blank=True, max_length=35, null=True)),
                ('reservation_by_phone', models.CharField(blank=True, max_length=23, null=True)),
                ('reserve_checkin_date', models.DateField()),
                ('reserve_checkout_date', models.DateField(blank=True, null=True)),
                ('no_adults', models.SmallIntegerField(blank=True, null=True)),
                ('no_child_0_5', models.SmallIntegerField(blank=True, null=True)),
                ('no_child_6_12', models.SmallIntegerField(blank=True, null=True)),
                ('no_babies', models.SmallIntegerField(blank=True, null=True)),
                ('meal_plan', models.CharField(blank=True, max_length=2, null=True)),
                ('billing_instructions', models.TextField(blank=True, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=15, null=True)),
                ('reserved_by', models.IntegerField()),
                ('date_reserved', models.DateField(blank=True, null=True)),
                ('confirmed_by', models.IntegerField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('roomid', models.IntegerField()),
                ('billed', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotele.agent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotele.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.SmallIntegerField()),
                ('roomname', models.CharField(blank=True, max_length=35, null=True)),
                ('noofrooms', models.SmallIntegerField(blank=True, null=True)),
                ('occupancy', models.SmallIntegerField(blank=True, null=True)),
                ('tv', models.BooleanField(default=False)),
                ('aircondition', models.BooleanField(default=False)),
                ('fun', models.BooleanField(default=False)),
                ('safe', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('V', 'Vacant'), ('R', 'Reserved'), ('B', 'Booked'), ('L', 'Locked')], default='V', max_length=1)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('filetype', models.CharField(blank=True, max_length=50, null=True)),
                ('roomtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotele.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotele.user')),
            ],
        ),
        migrations.CreateModel(
            name='UsersOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotele.user')),
            ],
        ),
    ]
