# Generated by Django 5.1.1 on 2024-12-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotele', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass_field',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='room',
            name='aircondition',
            field=models.BooleanField(default=False, verbose_name='هل تحتوي الغرفة على تكييف؟'),
        ),
        migrations.AlterField(
            model_name='room',
            name='fridge',
            field=models.BooleanField(default=False, verbose_name='هل تحتوي الغرفة على ثلاجة؟'),
        ),
        migrations.AlterField(
            model_name='room',
            name='fun',
            field=models.BooleanField(default=False, verbose_name='هل تحتوي الغرفة على مروحة؟'),
        ),
        migrations.AlterField(
            model_name='room',
            name='safe',
            field=models.BooleanField(default=False, verbose_name='هل تحتوي الغرفة على صندوق أمانات؟'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('V', 'شاغر'), ('R', 'محجوز'), ('B', 'تم الحجز'), ('L', 'مغلق')], default='V', max_length=1, verbose_name='حالة الحجز'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tv',
            field=models.BooleanField(default=False, verbose_name='هل تحتوي الغرفة على تلفزيون؟'),
        ),
    ]
