# Generated by Django 5.1.1 on 2024-12-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotele', '0002_rename_pass_field_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
