# Generated by Django 5.1.4 on 2025-04-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('damage_id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الضرر')),
                ('damage_type', models.CharField(choices=[('بشري', 'بشري'), ('مادي', 'مادي')], max_length=50, verbose_name='نوع الضرر')),
                ('male_deaths', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد وفيات الذكور')),
                ('female_deaths', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد وفيات الإناث')),
                ('male_injuries', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد إصابات الذكور')),
                ('female_injuries', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد إصابات الإناث')),
                ('material_damage_description', models.TextField(blank=True, null=True, verbose_name='وصف الضرر المادي')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='crimes.crime', verbose_name='الجريمة')),
            ],
            options={
                'verbose_name': 'ضرر',
                'verbose_name_plural': 'الأضرار',
                'unique_together': {('crime', 'damage_type', 'male_deaths', 'female_deaths')},
            },
        ),
    ]
