# Generated by Django 5.1.4 on 2025-04-14 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('suspect_id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم المتهم')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الثلاثي')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللقب')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('nationality', models.CharField(max_length=50, verbose_name='الجنسية')),
                ('country', models.CharField(max_length=50, verbose_name='البلد')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(120)], verbose_name='العمر')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='يجب أن يحتوي على أرقام فقط', regex='^[0-9]+$')], verbose_name='رقم الهاتف')),
                ('residence', models.CharField(max_length=200, verbose_name='محل الإقامة')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة')),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='جهة العمل')),
                ('marital_status', models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], max_length=20, verbose_name='الحالة الاجتماعية')),
                ('education_level', models.CharField(max_length=50, verbose_name='المستوى التعليمي')),
                ('relationship_with_victim', models.CharField(blank=True, max_length=100, null=True, verbose_name='علاقة بالمجني عليه')),
                ('role_in_crime', models.TextField(verbose_name='دور في الجريمة')),
                ('face_encoding', models.JSONField(blank=True, null=True, verbose_name='بصمة الوجه')),
                ('is_fugitive', models.BooleanField(default=False, help_text='إذا تم اختياره يعني المتهم هارب، وإلا يعتبر مقبوض', verbose_name='هارب؟')),
                ('preventive_detention_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحبس الاحتياطي')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإفراج')),
                ('crimes', models.ManyToManyField(related_name='suspects', to='crimes.crime', verbose_name='الجرائم المرتبطة')),
                ('previous_crimes', models.ManyToManyField(blank=True, related_name='related_suspects', to='crimes.crime', verbose_name='الجرائم السابقة')),
            ],
            options={
                'verbose_name': 'متهم',
                'verbose_name_plural': 'المتهمون',
                'ordering': ['-suspect_id'],
                'unique_together': {('full_name', 'age', 'phone')},
            },
        ),
    ]
