# Generated by Django 5.1.1 on 2024-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=100)),
                ('operation_date', models.DateField()),
                ('operation_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
