# Generated by Django 5.1.1 on 2024-11-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operation_type',
        ),
    ]
