# Generated by Django 5.1.1 on 2024-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_operation_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('donation', 'متبرع'), ('distribution', 'توزيع')], default='distribution', max_length=100),
            preserve_default=False,
        ),
    ]
