# Generated by Django 5.1.1 on 2024-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('donation', 'متبرع'), ('distribution', 'توزيع')], max_length=100, null=True),
        ),
    ]
