# Generated by Django 5.1.1 on 2024-10-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('lab_technician', 'Lab Technician'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('manager', 'Manager')], max_length=20),
        ),
    ]
