# Generated by Django 5.1.1 on 2024-10-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_first_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
