# Generated by Django 5.1.1 on 2024-11-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unkown', max_length=100)),
                ('last_name', models.CharField(default='Unkown', max_length=100)),
                ('age', models.PositiveIntegerField(default=30)),
                ('specialization', models.CharField(default='General', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='doctor_images/%y/%m/%d')),
                ('file_report', models.FileField(null=True, upload_to='doctor_files/%y/%m/%d')),
                ('upload_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bio', models.TextField(default='Biography not provided', max_length=500)),
            ],
        ),
    ]
