# Generated by Django 5.1.1 on 2024-11-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctor_first_name_alter_doctor_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(default='Unkown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(default='Unkown', max_length=100),
        ),
    ]
