# Generated by Django 5.1.1 on 2024-11-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_remove_doctor_first_name_remove_doctor_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='firstname',
            new_name='firstD_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='lastname',
            new_name='lastD_name',
        ),
    ]
