# Generated by Django 5.1.1 on 2024-12-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('action', models.TextField()),
                ('action_date', models.DateTimeField()),
            ],
        ),
    ]
