# Generated by Django 5.1.4 on 2025-01-01 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25, verbose_name='الاسم الأول')),
                ('sname', models.CharField(max_length=25, verbose_name='الاسم الأخير')),
                ('loginname', models.CharField(max_length=15, unique=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صالح', regex='^\\+?1?\\d{9,15}$')], verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=65, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='البلد')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('user', 'مستخدم عادي')], default='user', max_length=10, verbose_name='الدور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'indexes': [models.Index(fields=['loginname'], name='Users_user_loginna_b48964_idx'), models.Index(fields=['email'], name='Users_user_email_d939c8_idx')],
            },
        ),
    ]
