# Generated by Django 5.1.1 on 2024-12-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'فردية'), ('double', 'مزدوجة'), ('family', 'عائلية'), ('apartment', 'شقة'), ('suite', 'جناح')], max_length=50)),
                ('number_of_rooms', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('booked', 'محجوزة'), ('maintenance', 'صيانة')], max_length=20)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(choices=[(1, '1 شخص'), (2, '2 أشخاص'), (3, '3 أشخاص'), (4, '4 أشخاص'), (5, '5 أشخاص')])),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
