# Generated by Django 5.1.4 on 2024-12-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'غرفة', 'verbose_name_plural': 'غرف'},
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
