# Generated by Django 5.1.4 on 2024-12-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomes', '0002_alter_room_options_room_room_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image_url',
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
