# Generated by Django 5.1.4 on 2025-01-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unludd', max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(default='091133333', max_length=15, verbose_name='رقم الهاتف')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3, verbose_name='فصيلة الدم')),
                ('quantity', models.DecimalField(decimal_places=2, default='00', max_digits=5, verbose_name='الكمية المطلوبة')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة الطلب')),
            ],
        ),
    ]
