# Generated by Django 5.1.1 on 2024-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='health_status',
            field=models.CharField(choices=[('معتمد', 'Approved'), ('غير معتمد', 'Not Approved')], max_length=20),
        ),
    ]
