# Generated by Django 5.1.1 on 2024-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donor_health_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'Male'), ('انثى', 'Female')], max_length=5),
        ),
    ]
