# Generated by Django 5.1.1 on 2024-11-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
    ]
