# Generated by Django 5.1.4 on 2025-01-30 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الجريمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'نوع الجريمة',
                'verbose_name_plural': 'أنواع الجرائم',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20, unique=True, verbose_name='الرقم المرجعي')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('description', models.TextField(verbose_name='تفاصيل البلاغ')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('investigating', 'قيد التحقيق'), ('closed', 'مغلق')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='بلاغ مجهول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.crimetype', verbose_name='نوع الجريمة')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المُبلغ')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
            },
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/', verbose_name='الملف')),
                ('file_type', models.CharField(max_length=10, verbose_name='نوع الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reports.report')),
            ],
            options={
                'verbose_name': 'ملف مرفق',
                'verbose_name_plural': 'الملفات المرفقة',
            },
        ),
    ]
