# Generated by Django 5.1.4 on 2025-01-31 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'بلاغ', 'verbose_name_plural': 'البلاغات'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='crime_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/attachments/', verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Usss', max_length=200, verbose_name='عنوان البلاغ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='وصف البلاغ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('under_investigation', 'قيد التحقيق'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'قيد المعالجة'), ('under_investigation', 'قيد التحقيق'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحديث')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reports/updates/attachments/', verbose_name='مرفقات')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_updates', to=settings.AUTH_USER_MODEL, verbose_name='تم التحديث بواسطة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reports.report', verbose_name='البلاغ')),
            ],
            options={
                'verbose_name': 'تحديث البلاغ',
                'verbose_name_plural': 'تحديثات البلاغات',
                'ordering': ['-created_at'],
            },
        ),
    ]
