# Generated by Django 5.1.4 on 2025-04-14 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('victim_id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم المجني عليه')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الثلاثي')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللقب')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('nationality', models.CharField(max_length=50, verbose_name='الجنسية')),
                ('country', models.CharField(max_length=50, verbose_name='البلد')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='العمر')),
                ('residence', models.CharField(max_length=200, verbose_name='محل الإقامة')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='يجب أن يبدأ رقم الهاتف بـ 7 ويتكون من 9 أرقام', regex='^7\\d{8}$')], verbose_name='رقم الهاتف')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة')),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='جهة العمل')),
                ('education_level', models.CharField(max_length=50, verbose_name='المستوى التعليمي')),
                ('marital_status', models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], max_length=20, verbose_name='الحالة الاجتماعية')),
                ('crimes', models.ManyToManyField(related_name='victims', to='crimes.crime', verbose_name='الجرائم المرتبطة')),
            ],
            options={
                'verbose_name': 'مجني عليه',
                'verbose_name_plural': 'المجني عليهم',
                'ordering': ['-victim_id'],
                'unique_together': {('full_name', 'age', 'phone')},
            },
        ),
    ]
