# Generated by Django 5.1.1 on 2024-11-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
