# Generated by Django 5.1.1 on 2024-11-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_patient_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.PositiveIntegerField(default=18, max_length=20),
        ),
        migrations.AddField(
            model_name='patients',
            name='file_report',
            field=models.FileField(null=True, upload_to='files/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='patients',
            name='report',
            field=models.TextField(default=100, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
