# Generated by Django 5.1.1 on 2024-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patients_age_patients_file_report_patients_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
