# Generated by Django 5.1.4 on 2024-12-31 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomes', '0003_remove_room_room_image_url_room_room_image'),
        ('reservations', '0002_reservation_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Roomes.room'),
        ),
    ]
